-- mysql/init.sql
CREATE DATABASE IF NOT EXISTS tarjetas_db;
USE tarjetas_db;

CREATE TABLE IF NOT EXISTS TARJETA (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  numero VARCHAR(255) NOT NULL,
  fecha_expiracion DATE NOT NULL,
  cvv VARCHAR(255) NOT NULL
);